### ISSUE TITLE
vscode-journal causes latex formula rendering in markdown to fail

### ISSUE THREAD

**Issue by kuzen** [pajoma/vscode-journal#102]
Issue Type: <b>Bug</b>

It cannot render the latex formula `$\left| x \right|$`

Extension version: 0.11.2
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22523
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.35GB (5.55GB free)|
|Process Argv|--crash-reporter-id 1d6afbd1-b603-475f-9947-3c243102c79a|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by kuzen** [comment]
same as #101

**Comment by pajoma** [comment]
A new milestone release has been added which addresses this bug. Can you please test (download it [here](https://github.com/pajoma/vscode-journal/releases/tag/0.12.M1)) and verify?
