### ISSUE TITLE
Add a journal entry per week (e.g. 2022 > 3 > W13.md)

### ISSUE THREAD

**Issue by roxberry** [pajoma/vscode-journal#103]
I'd like to be able to manage my weekly status notes with journal.  Can vscode-journal do this now?  Figure it would drop in the month folder, 2022>3>W13.md?

**Comment by edthedev** [comment]
I would use this feature as well, if it were available.

**Comment by pajoma** [comment]
Good idea, should be easy to implement. 

Keywords for input could be

- next week to open next week's page
- last week 
- w13 to open a specific (work week)
- task next week prepare the slides
- etc..

Localization might be tricky. Weeks start on different days depending on your region.

**Comment by edthedev** [comment]
I personally, wouldn't mind much about localization, as long as the same file is opened each time the command runs.

Honestly, even if the command resulted in a file named 'W3.md' that would cover my use case just fine.
