### ISSUE TITLE
Older Notes not showing up in the "Select/Create a Note"

### ISSUE THREAD

**Issue by sklarsa** [pajoma/vscode-journal#130]
I recently upgraded the VSCode Journal plugin (now running v1.0.1) and notes older than around a month have disappeared from the dropdown.  I verified that the markdown files are still in the `~/Journal` directory structure.  Is this a known issue?

I uninstalled and reinstalled the plugin, but the behavior still exists

**Comment by pajoma** [comment]
Yes, I have the same issue (didn't notice before). Thanks for the bug report, I will look into it.

**Comment by sklarsa** [comment]
@pajoma, this bug just hit me again yesterday running v1.0.1 :-( Would it be possible to cut a new release to fix it?  Thank you very much for this awesome extension!
