### ISSUE TITLE
Disable syntax highlighting entirely

### ISSUE THREAD

**Issue by douglance** [pajoma/vscode-journal#136]
I use a different extension to highlight my task checkboxes, so I would like to disable `vscode-journal` checkbox syntax highlighting. Is that possible with the current codebase? Where would I look to implement that change?

**Comment by pajoma** [comment]
This happens on startup in the registerSyntaxHighlighting Method:  https://github.com/pajoma/vscode-journal/blob/develop/src/ext/startup.ts

VSCode's behaviour changed significantly since I've implemented this, I think it can be dropped.

**Comment by pajoma** [comment]
Can you give me a link to the other extension for testing?
