### ISSUE TITLE
Support for VS Codium

### ISSUE THREAD

**Issue by allanbowe** [pajoma/vscode-journal#138]
For the FLOSS lovers out there, would you consider packaging the extension on https://open-vsx.org/ so that it can be used in VS Codium?

**Comment by allanbowe** [comment]
Would there be any objection if I was to package it for you?  I could create an org, set it up, and then make you admin..

**Comment by pajoma** [comment]
I will look into it this week. I want to setup a pipeline via github actions to remove the manual packaging step first.

**Comment by allanbowe** [comment]
You did it - thanks!!!
