### ISSUE TITLE
Journal: Add option to disable opening journal when using quick memo

### ISSUE THREAD

**Issue by mohamed-albgal** [pajoma/vscode-journal#145]
Hello. This extension is awesome and I'm appreciative of the work you've put into this. Is there a way to enable the quick add feature to not open a new tab showing the entry? I usually want to dump a quick memo and resume instead of closing the newly created tab?

**Comment by pajoma** [comment]
Implemented, see animation

![#145](https://github.com/pajoma/vscode-journal/assets/92156/da95bd7c-9f83-4c6a-9775-cabe87adcbb0)
