### ISSUE TITLE
Bug: When I create two memos in the same minute, the latter memo overwrites the former memo.

### ISSUE THREAD

**Issue by PamlJam** [pajoma/vscode-journal#147]
When I create two memos in the same minute, the latter memo overwrites the former memo.

I just guess if append some random numbers to **minute time** will fix the bug.

PS. I fell in love with `vscode-journal` immediately when I found it earlier today.

**Comment by pajoma** [comment]
Can't reproduce, did you configure a special pattern for printing your memos in your journal template settings?

![#147](https://github.com/pajoma/vscode-journal/assets/92156/0096653c-6486-4924-8f77-e9d6ce03efd1)

**Comment by PamlJam** [comment]
Oh, I cann't reproduce it now too.

Maybe I just got something wrong at the time. 

I shall close the issue.
