### ISSUE TITLE
When first word in a memo or task starts with n that character is lost / removed

### ISSUE THREAD

**Issue by smarkwart** [pajoma/vscode-journal#156]
Hello, 

I just made the experience that when I enter a note or task which starts with letter n, like "task new", that character is somehow lost / removed.

How to reproduce:
Create a new task with "task new stuff"

Expected outcome: 
A new task is created which contains the text "new stuff"

Observed outcome:
A new task is created which contains the text "ew stuff"

I'm using v1.0.1 currently

**Comment by pajoma** [comment]
Thanks for fixing it
