### ISSUE TITLE
change the file link's backward slash to forward slash?

### ISSUE THREAD

**Issue by beef-potato** [pajoma/vscode-journal#158]
As it is fine to use backward slash in windows. the file link will cause some problem in github web view. 

the backward slash will be seen as %5C, file link won't work with that in web browser. 

I read the settings, and it  seems there is no way to change it?

![journal1](https://github.com/pajoma/vscode-journal/assets/95594775/d598e7fb-19e0-4d82-8382-5df1bee361ca)
![journalgithub](https://github.com/pajoma/vscode-journal/assets/95594775/1e801f96-4218-40bb-a002-f53f93ccabed)

**Comment by pajoma** [comment]
All links are now using slashes instead of backslashes (VSCode is handling them equally)
