### ISSUE TITLE
a few suggestions/issues

### ISSUE THREAD

**Issue by rbenson** [pajoma/vscode-journal#18]
- Have you thought about maybe flattening the structure? As is I see this being useful if you need to do daily break downs, or bullet journal type stuff, but if you don't need that level of detail, it is hard to use.  I am seeking an orgmode replacement. If I know I made a note somewhere, how can I easily get to it?  
- have you thought about adding in your own language syntax? this would be useful if you want to give task/MEMO unique looks  
- I get "Journal input not recognized" when making a memo, even the sample you have in the readme

**Comment by pajoma** [comment]
Hi, good questions: 

1) I am not sure I've fully understand the "flattening" part. Could you give an example of an higher level of detail (e.g. define a task on a week level should be doable)

2) "Browsing to the notes" is on my todo list. #8 tracks this issue. Next release should include the new view in sidebar feature, which came in the latest vscode version. I'd like to try a calendar widget, with pages having notes or todos being marked as such. 

3) Can you maybe give an example, which is not yet covered by the settings? (I know, I should probably make the document this better)

4) I'll look into it. Happens sometimes to me as well, will be covered in the next release.

**Comment by rbenson** [comment]
Hi there,

1- Most of my projects span anywhere from a few weeks to almost a year,  and a fair amount of they don't have daily activities. If I open today's log, note something, it may be impossible to find in 1+ weeks. I guess I could keep a master file and link everything afterwards,  but putting everything in a master would be easier.

is your third item in your list in regards to my syntax suggestion?

**Comment by pajoma** [comment]
Opened a new issue #19 regading the "flattening" for projects. 

3) Yes, I am note what you mean about the unique looks. 

I used asciidoc when I started this project and switched to markdown. The extension is synax-independent, format and structure is defined in the settings (with default using markdown). My tasks list looks like this

```
*Tasks*
- [ ] TODO: Something to think about
- [x] TODO: Another thing I thought about
```
The settings for this are
```
"journal.tpl-task": "- [ ] TODO: {content}", 
"journal.tpl-task-after": "*Tasks*",
```

**Comment by rbenson** [comment]
I was thinking about giving keywords special looks, like TODO: bold and red.

**Comment by pajoma** [comment]
Ah, you are thinking about syntax highlighting. Yes, should be doable, I will look into it.

**Comment by rbenson** [comment]
I am gueessing ext can extend a language vs having to override it

**Comment by flyisland** [comment]
> I'd like to try a calendar widget

@pajoma, I'm looking forward to this widget, when'll it available on vscode-journal?

**Comment by pajoma** [comment]
The calendar widget is a bit complicated, since the views extension (in the sidebar) only supports tree-like structures. It's on my todo list (but not coming anytime soon).

**Comment by pajoma** [comment]
Regarding the widget: please checkout [this extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.vscode-journal-view)

**Comment by pajoma** [comment]
Syntax highlighting in its first version is now in 0.6.0

**Comment by pajoma** [comment]
All suggestions are implemented in new version.
