### ISSUE TITLE
Request: Configurable filename and path options

### ISSUE THREAD

**Issue by beansprout** [pajoma/vscode-journal#20]
### I love this extension.  
Very simple, easy to use, and I love that everything saves as a text file and I can configure the file extension.

### The only thing I wish I could change is:
* the filename ( to full date for example YYYY_MM_DD) 
* and change the path to a single path rather than nested in folders.  

I use Nvalt for notes and it would be nice to keep everything in one flat folder so if I'm not in VS Code I can pull up the file from the Nvalt folder, and in Notesy on my phone.  Nvalt doesn't look in nested folders.  

If I get some time I might try to code it myself but I'm still a novice so I'm not sure if I can do it.  

So...  if it's something really easy to do, feel free to just pop in that feature for me :)

**Comment by pajoma** [comment]
Hey, good suggestion. I guess the easiest would be a new option to set the save pattern using the [date and time formats](https://www.w3.org/TR/NOTE-datetime) eg. 

```journal.path = "%YYYY%/%MM%/%DD%" ```

or in your case 

```journal.path = "%YYYY%_%MM%_%DD%" ```

**Comment by pajoma** [comment]
So, what's missing here is a good solution for storing notes in a flat file structure. Probably best is a new setting like this: 

```
journal.path = "%YYYY%/%MM%/%DD%"
journal.pathNodes = "notes/%YYYY%"

Example: 
/notes/2017/My_First_Note.md
/notes/2017/My_Second_Note.md
2017-05-23.md
2017-05-24.md
```

**Comment by zvlades** [comment]
Hi. @pajoma, thanks, great extension. 

If it is valuable for anybody else, I would happy if you add support for formats with literal month and week-day representation, so user will be able to compose date like `2017-Sep-16-Sat` to use as file-name.

**Comment by jvlad** [comment]
Hi. @pajoma, thanks, great extension.

If it is valuable for anybody else, I would happy if you add support for formats with literal month and week-day representation, so user will be able to compose date like 2017-Sep-16-Sat to use as file-name.

**Comment by pajoma** [comment]
Works in new version, check the new settings description. All options usable for moment.js should work in path and file patterns.
