### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Pokom** [pajoma/vscode-journal#21]
Hi All,

For the past few months I have been taking notes by manually creating files, and switched over to VSCode a few weeks back and just found this extension. I wanted to see if there's anything I can do to help out? 

Feel free to immediately close this issue, I just want to figure out how to touch base :)

**Comment by pajoma** [comment]
Hi Pokom, 

I hope you find this extension useful. 

Regarding contributions: There are several open issues right now where I am looking for feedback about the possible solutions I wrote in the comments there. If you find one of the issues interesting and you like to work on it, just add your comment and describe how you would approach it. If we agree, give it a go. Just make sure you are working on your own branch.
