### ISSUE TITLE
Create new un-scoped notes.

### ISSUE THREAD

**Issue by pratuat** [pajoma/vscode-journal#22]
How can I create a note that would reside in root folder ?

Whenever I create a new note, it is created within the folder hierarchy of current day. Can't I create a note in root folder without scoping it by the date of creation ?

**Comment by pajoma** [comment]
Having them stored in a folder structured by dates was kind of the point. But your suggestion let me to rethink issue #20. I will try to come up with an idea (using the same approach). I'll track it there.

**Comment by pajoma** [comment]
Ah, one question: Do you want to have a choice between scoped and un-scoped notes?

**Comment by pratuat** [comment]
Just having a named note in the root directory would be fine for me. But if one can have named notes scoped(nested) within directories, that would be awesome too.

**Comment by pajoma** [comment]
Fixed in new version, path patterns are now configurable
