### ISSUE TITLE
Turn "open in new editor group" mode on/off

### ISSUE THREAD

**Issue by jvlad** [pajoma/vscode-journal#23]
_Initial state_: in my VSCode I have one or more open editors, all in one editor_group (editors area is not splitted)

_Action_: I run command like `journal: Today` (this specific command is example)

_Result_: today_journal_page is open in new editor_group (now my editors area is splitted vertically)

What I suggest is to have setting_item like `journal.openInNewEditorGroup: boolean`,  
so user can specify `false` to open journal_day in a new tab in the same editor_group.

**Comment by pajoma** [comment]
Good Idea, will do it.

**Comment by pajoma** [comment]
Part of release 0.6.0
