### ISSUE TITLE
4 suggestions

### ISSUE THREAD

**Issue by TheKiteRunning** [pajoma/vscode-journal#30]
Hi,

Thank you for your time. I have used this extension for two months, and here are my 4 suggestions:

1. when I open a new diary, the cursor will be located in the beginning of the document, followed with the title. However, we always start our writing from the end of the document.

![image](https://user-images.githubusercontent.com/24802332/40398839-8dfc569c-5e6c-11e8-9131-847825659998.png)

2. support quick notes like [vscode-memo_quicknote](https://github.com/satokaz/vscode-memo-life-for-you)

 ![quicknote](https://raw.githubusercontent.com/satokaz/vscode-memo-life-for-you/assets/images/vscode-memo_quicknote.gif)

3. command to list all the diaries and notes for every week, month, and year, I think a dynamically upgraded index file may work.

4. support the setting option of excluded folder for note file monitor, since I always create image folder, and would rather they not displayed in the diary file like the below

- NOTE: `[(image) ](./23/image)`

hope you can consider these

best wishes

**Comment by pajoma** [comment]
Thanks for your suggestions. 

1) I check if this is possible, shouldn't be a problem
2) What exactly do you mean here? Do you refer to missing functions (Quick notes and memos are the main goal of this extension) or the usability? I had a look at https://github.com/mattn/memo, the commands there could be an option
3) I had a look at the new [webview api](https://code.visualstudio.com/updates/v1_23#_webview-api), which might help here. I thought about creating (and automatically updating) markdown files for the week, month and year. Those simply link to the journal entries (daily pages) and notes, as well as show the number of open tasks. A new command (e.g. journal browse) would directly open the markdown preview page. 
4) I can introduce the new config options to exclude files by sub-directory and by file-type

**Comment by TheKiteRunning** [comment]
Thanks for your help, it means a lot. 
With regard to question 2, I suggest a new function that we can choose to take a quick note without opening the `today` document, however, the quick note can be appended to the `today` document automatically with the adding time as title. The function is demonstrated in a similar extension  [vscode-memo_quicknote](https://github.com/satokaz/vscode-memo-life-for-you), and command is:  `Memo: Today's quick Memo - Append to the file of today's date`

**Comment by pajoma** [comment]
You have two options to add memos (Let's say "do shopping today"

- via the journal:memo command (it will append to today's file) and enter "do shopping today" in the input box
- via Strg+Shift+J and then just enter text "do shopping today" to add it to today's page or "+1 do shopping today" to add it to tomorrow (or "tomorrow I have to go shopping" or "next wednesday I have to go shopping")

**Comment by TheKiteRunning** [comment]
Thank uuu verrrry muuuch!!!

**Comment by pajoma** [comment]
Moving cursor position to end of file is part of 0.6.0

**Comment by pajoma** [comment]
The suggestion to ignore files is now tracked in #31

**Comment by pajoma** [comment]
The suggestion about browsing is tracked in #7 

Closing this ticket now.
