### ISSUE TITLE
Notes command not creating local links

### ISSUE THREAD

**Issue by jm-welch** [pajoma/vscode-journal#32]
# Info
Mac OS X 10.13.4
Visual Studio Code 1.23.1
Journal 0.6.0

# Issue details

`Journal: Notes` command does not create local link

## Steps
1. `Cmd-Shift-P`
2. Select the `Journal: Notes` command
3. Enter a note name in the field and press enter

## Expected behavior
1. New note file is created in `$year/$month/$day` path with name provided in step 3 above
2. Local link to new note is placed in today's journal page

## Observed behavior
1. New note file is created
2. No local link is created

# Custom settings

```JSON
{
    "journal.tpl-entry": "# [Journal Entry for] dddd, MMMM Do YYYY[\n\n## Tasks\n\n## Notes\n]",
    "journal.tpl-task-after": "## Tasks",
    "journal.tpl-todo-after": "## Tasks",
    "journal.tpl-note": "# ${input}\n",
    "journal.tpl-files-after": "## Notes",
    "journal.tpl-memo-after": "## Notes"
}
```

I have also removed all of the custom settings, closed and relaunched VSCode, and tried again, with the same results.

**Comment by jm-welch** [comment]
Just rolled back to 0.5.0 manually, and the local link creation works fine in that version.

**Comment by pajoma** [comment]
Thanks, I will look into it

**Comment by pajoma** [comment]
Sorry, I can't reproduce this error. I will refactor the debug messages for the notes feature and provide a Beta-version here. Perhaps then we can isolate the issue.

**Comment by pajoma** [comment]
Should be working with the new version, can you try it out?

**Comment by jm-welch** [comment]
It's been forever, but this does appear to have been fixed.
