### ISSUE TITLE
journal:note inserts memo instead of new md file

### ISSUE THREAD

**Issue by beyondtheteal** [pajoma/vscode-journal#39]
<img width="552" alt="screen shot 2018-08-02 at 5 58 40 pm" src="https://user-images.githubusercontent.com/39837332/43613566-d322d9f0-967d-11e8-9e21-9b104d6f7898.png">

No matter how I seem to type in `journal:note`, it always inserts a memo instead of a new markdown file. I also don't see an auto-complete option like in the .gif. 

MacOS 10.13.6
VS Code 1.25.1 
vscode-journal 0.9.0
vscode-journal-view 0.0.14

**Comment by pajoma** [comment]
`journal:note` is a command, which you have to enter in the command palette, see also here: https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette. You open it via `ctrl+shift+p`

You cannot create a note using the input using the journal's smart input (for the lack of a better name ;), which is opened by the `Ctrl+Shift+J` shortcut. Any text you enter which is not recognized as date or task will be printed as memo to today's page. 

I updated the docs.

**Comment by beyondtheteal** [comment]
Great! Thank you - user error in not knowing what the command palette in VS Code was. 

On [this page](https://github.com/pajoma/vscode-journal/blob/master/docs/notes.md), it'd be helpful to have the ctrl+shift+P command listed, as seeing just the ctrl+shift+J shortcut is what caused my confusion here.
