### ISSUE TITLE
Browse through previous notes

### ISSUE THREAD

**Issue by pajoma** [pajoma/vscode-journal#4]
> One thing I miss is browsing my previous notes through VSCode, rather than finding them on the disc.

Not sure how to implement this for now. There is an extension point to show a selection as list. But this isn't really an option to browse through a calendar.

Possible solutions:
1. new command "journal:browse" which opens a new vscode instance with the journal as workspace. 
2. Content Provider which renders the current journal in a text document. The individual entries are linked

Second option could be useful to display days with open tasks (see issue #3)

**Comment by edthedev** [comment]
I think option 1 above makes a lot of sense.

I personally worked around this issue by setting "journal.base" in VSCode user settings to a folder that I always have open in VSCode anyway.

Option 1 above would be a nice alternative to always having that window open; and would benefit me by helping me open it quickly from other VSCode instances, as well.

**Comment by pajoma** [comment]
New Command "journal:open" implemented, which opens a new instance of vscode with the journal base directory as root.
