### ISSUE TITLE
Critical override of user styles

### ISSUE THREAD

**Issue by ricardomatias** [pajoma/vscode-journal#40]
After installing the plugin, I lost all of my user defined color theme override styles. This happened at `editor.tokenColorCustomizations { textMateRules: [] }`.

Really annoying to get this. Please fix for the sake of others.

**Comment by pajoma** [comment]
Will be fixed next week, thanks for letting me know.

Ricardo Matias <notifications@github.com> schrieb am Mi., 22. Aug. 2018,
11:08:

**Comment by pajoma** [comment]
Fixed in new version
