### ISSUE TITLE
Add notes that are not bound to a specific day

### ISSUE THREAD

**Issue by cars10w** [pajoma/vscode-journal#43]
Right now you can add notes for a specific day/date (ie. for today) only.

I would like to collect and maintain notes without any day/date dependency within vscode-journal. Also some kind of organization/hierarchy/tagging of those notes would be helpful.

**Comment by pajoma** [comment]
Yes, that would be helpful, and I am getting closer with each release. 

With the current version you can already configure the file and path patterns used for your notes. You can just omit anything date related. Be aware, this will break support for "vscode-journal-view" extension. 

With one of the next releases, you will be able to "scope" your notes. 

The idea is: When you create a new note and enter a title, you prefix it with a tag, e.g. "#pro12 Meeting minutes for Project 12". If you've defined a file/path-Pattern for the tag "#pro12", this note will be created in this directory.  

I thought about hierarchies, but I think that will be complicating things too much.

**Comment by cars10w** [comment]
Thanks for your feedback!  If I can aggregate all notes marked with the same tag, and can list/access them in an easy manner this way, then this would be sufficient.  :+1:

**Comment by edthedev** [comment]
Oh, I like the scope idea.

Honestly, just dropping them into the month folder instead of by day would get a lot more visibility.

I'll probably use scopes once they're available.

**Comment by edthedev** [comment]
@pajoma @cars10w 

I believe this issue can be closed, as [scopes](https://github.com/pajoma/vscode-journal/blob/develop/docs/scopes.md#scopes) now provide this functionality.

I'm using a simple top level `meeting` scope, and all of my notes drop there as long as I prefix them with `#meeting`.

**Comment by edthedev** [comment]
Here's the settings that accomplish this for me:

```json
"journal.scopes": [
        {
            "name": "meeting", 
            "patterns": {
              "notes": {
                "path": "${base}/Meeting",
                "file": "${d: YYYY-MM}/${input}.${ext}"
              }, 
            }
        }, 
    ],
    "journal.templates": [
        {
            "name": "note",
            "template": "---\ntitle: ${input}\nauthor: <me>\ndate: ${d:dddd, MMMM DD YYYY}\n---\n\n## Context\n\n## Notes\n\n## Actions\n\n"
        }
    ]
```

Then to create a note in `Meeting\2022-07` I would hit `Ctrl+Shift+J`, select `Select / create a note`, and type `#meeting <and then the meeting topic>`.

**Comment by edthedev** [comment]
Notes can also be redirected to i.e. just the year folder with the following configuration or similar (this did not work in a previous release, but now does):
```json
"journal.patterns": {
        "notes": {
            "path": "${base}/${year}/",
            "file": "${month}-${input}.${ext}"
        },
}
```

**Comment by pajoma** [comment]
Thanks for the update. Yes, the patterns and scopes address this requirement.
