### ISSUE TITLE
Toggle panel doesn't work.

### ISSUE THREAD

**Issue by cfaguilera20** [pajoma/vscode-journal#45]
When I click CMD + J the panel doesn't toggle.

**Comment by pajoma** [comment]
That should be `CMD+SHIFT+J`. You can check the shortcut by opening the associated command `CMD-SHIFT-P` and find the command "Journal: Enter specific day"

**Comment by thiagodebastos** [comment]
I think the OP means that CMD+J is being overridden by this plugin, so they can't open VSCode's panel. I've been experiencing this issue for a while and tracing it back to vscode-journal was a real pain.
