### ISSUE TITLE
plugin overrides `CMD+J` key binding

### ISSUE THREAD

**Issue by thiagodebastos** [pajoma/vscode-journal#47]
With this extension installed, I have no access to CMD+J as a keybinding. This is VSCode's default binding for toggling the panel.
With this extension installed, CMD+J starts a chord sequence and waits for the next chord, rather than toggling VSCode's panel.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/6151341/60581536-5c5c0580-9dca-11e9-85ca-058804ccde7a.png">

This was hard to track down since the binding does not appear in the Keyboard Shortcuts screen:
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/6151341/60581638-94fbdf00-9dca-11e9-9d15-6dd5c7c120b9.png">

As a workaround for now, I've added the following to `keybindings.json`:
```json
  {
    "key": "cmd+j",
    "command": "workbench.action.togglePanel"
  },
```

**Comment by pajoma** [comment]
Ok, I'm not sure anymore why I used the "CMD+J D/S/T" shortcut for the macro functions within notes, either by mistake or because I assumed that they don't interfere with shortcuts without a second key. 

Fixed in new build, all shortcuts are using SHIFT now as second modifier (CMD+SHIFT+J).

**Comment by thiagodebastos** [comment]
Thankyou @pajoma. I want to take some time to learn more about extension development, that way I can help next time. Thank you for your time.
