### ISSUE TITLE
Template in new Settings UI

### ISSUE THREAD

**Issue by kenlefeb** [pajoma/vscode-journal#49]
I just filed a [bug report](https://github.com/microsoft/vscode/issues/79571) with the VS Code team, but I think you should probably add some verbiage to your setting for the template string (`tpl-entry`) to alert the user that they need to use `settings.json` to directly edit the template string, because they will escape the `\n` characters which is pretty important to a good template string.

**Comment by pajoma** [comment]
Good point. It's a bit annoying that you don't have the option anymore in the settings editor to switch to the json view. Will update the comments.
