### ISSUE TITLE
Generated Markdown is not markdown spec compatible

### ISSUE THREAD

**Issue by niderhoff** [pajoma/vscode-journal#55]
The generated markdown is not compatible with the markdownlint default settings ([see here](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)).

Maybe spacing after headings etc. should be configurable?

I know I can change my markdownlint settings, but it should really be the other way round I think and a lot of people might be using markdownlint anyway so we should give an option to make vscode journal compatible.

![image](https://user-images.githubusercontent.com/5991543/74815081-d65ce280-52f8-11ea-8219-c3fbffeb64c5.png)

![image](https://user-images.githubusercontent.com/5991543/74815117-ed033980-52f8-11ea-8521-d0f8e05f047a.png)

Solutions I could suggest:

A. make spacing after headings configurable
B. make a setting ("fix markdown automatically") that triggers the "fix all all violations in documents" (`markdownlint.fixAll`) of markdownlint if markdownlint is installed

**Comment by tisseurdetoile** [comment]
Hello 

does your "journal.tpl-entry": 

match the default one 

```json
"journal.tpl-entry":# ${weekday}, ${localDate}\n\n## Tasks\n\n## Notes\n\n
```

It seem your config lack the "\n\n" after ${localDate} and Tasks and note note.

You must edit the vscode settings.json directly.

**Comment by niderhoff** [comment]
I changed it manually at some point and added the \n\n, so I cannot answer this question anymore. I will close this issue until somebody else has this problem.

**Comment by niderhoff** [comment]
Hello,

I just installed vscode journal on a different PC and the same thing happened. Note that I have NOT set ANY options whatsoever. This is default behaviour after install.

**Comment by pajoma** [comment]
Taken your example, the issue seems to be where the memo is placed (directly after the header in this case), correct?

I am looking into it (hopefully in the weekend, quite busy atm)

**Comment by pajoma** [comment]
I have added the current prerelease to this project, can you please download it from [here](https://github.com/pajoma/vscode-journal/releases) and test it? 

To test, use the option "Install from VSIX..." in the Extension View of Visual Studio Code.
