### ISSUE TITLE
Change filename rules

### ISSUE THREAD

**Issue by JekRock** [pajoma/vscode-journal#57]
I think it would be easier to find a previously created note by entering the same text that was used when the note was created.
How it works now:

- CTRL+SHIFT+J -> Select/Create a note -> Type "My new note"
- Now let's try to open it. CTRL+SHIFT+J -> Select/Create a note -> Type "My new note". After typing "My " (with space) it will suggest creating a new note.
Suggestions don't work here because names of notes are normalized in [utils](https://github.com/pajoma/vscode-journal/blob/fd253b2deacb2582d7265d44148806ef8d4984db/src/util/util.ts#L191)
Maybe it's better not to remove spaces from the filename?

**Comment by pajoma** [comment]
Hmm, not sure if switching of normalization could break the extension for a few users. Probably better to switch it off through a new setting, which then supports your workflow when typing in the name of the existing note.

**Comment by pajoma** [comment]
In the new version, the input will show a list of previous versions with denormalized names. Does this approach match your needs?

**Comment by pajoma** [comment]
Denormalization approach seems to be working
