### ISSUE TITLE
Memo feature discards input sometimes

### ISSUE THREAD

**Issue by banjerluke** [pajoma/vscode-journal#59]
First, I'm so thrilled to have found your extension! I've been dreaming about something like this for a long time. Plain text rules. 😊

Unfortunately, I soon discovered that the Ctrl+Shift+J type-to-add-a-memo feature doesn't always work. There's a random chance that it will discard what I type and do nothing. For example, in this GIF it only was successful on attempts 3, 4, and 6 (of 7 total):

![memo adding bug screengrab](https://user-images.githubusercontent.com/15148/82734670-54060500-9cd1-11ea-89be-9086da04df1a.gif)

I am using a custom memo template (timestamped as I plan to use it for [interstitial journaling](https://medium.com/better-humans/replace-your-to-do-list-with-interstitial-journaling-to-increase-productivity-4e43109d15ef)):
```json
"journal.tpl-memo": "${d:HHmm} ${input}",
"journal.tpl-memo-after": "## Process",
```

Closing and reopening VS Code didn't help. Neither did disabling auto-save. It doesn't seem to matter whether the file being added to was previously open or not. Nothing shows up in the logs. I only have a few other extensions enabled: Remote SSH, Settings Sync, Sublime Text Keymap, and a few language-support extensions.

Let me know if there's anything else you'd like me to test!

**Comment by pajoma** [comment]
I will look into it. I already have a new version ready, which I am testing right now.

**Comment by pajoma** [comment]
Ok, this is a bit stupid. In my parsing rules a I decided that a memo string has to be longer then 6 letters, in your example you see that everything below is ignored.

**Comment by pajoma** [comment]
I have added the current prerelease to this project, can you please download it from [here](https://github.com/pajoma/vscode-journal/releases) and test it? 

To test, use the option "Install from VSIX..." in the Extension View of Visual Studio Code.

**Comment by banjerluke** [comment]
Works great! Thank you!


On May 26, 2020 at 7:36 AM, Patrick M (notifications@github.com) wrote:
I have added the current prerelease to this project, can you please download it from here ( https://github.com/pajoma/vscode-journal/releases ) and test it?
To test, use the option "Install from VSIX..." in the Extension View of Visual Studio Code.
