### ISSUE TITLE
Variables does not work when creating new memo

### ISSUE THREAD

**Issue by lahtite** [pajoma/vscode-journal#61]
I would like to include creating timestamp before memo line, but it seems that variables does not work there.

Settings.json
`"journal.tpl-memo": "- MEMO ${d:H.mm}: ${input}",
`
Result:
`- MEMO ${d:H.mm}: testnote`

**Comment by pajoma** [comment]
Does this problem still appear with the new version?

**Comment by pajoma** [comment]
Tested again, seems to work
