### ISSUE TITLE
Invalid date on Macbook pro Catalina

### ISSUE THREAD

**Issue by stampeder** [pajoma/vscode-journal#65]
The day comes up as Invalid Date NaNth in visual studio code journal on my mac. At first it all worked fine but then developed the problem. 

![image](https://user-images.githubusercontent.com/5720249/95872909-fd0ed400-0d34-11eb-8cd8-0955e8d5d43a.png)
![Screen Shot 2020-10-13 at 9 16 28 AM](https://user-images.githubusercontent.com/5720249/95872998-14e65800-0d35-11eb-8563-179264ebfe48.png)

Screen shot above shows the issue.

**Comment by pajoma** [comment]
You have a problem with the extension vscode-journal-view, which you can find [here](https://github.com/Gruntfuggly/vscode-journal-view). 

Do you have your own paths configured?

**Comment by pajoma** [comment]
Closed.
