### ISSUE TITLE
New notes using absolute paths instead of relative paths

### ISSUE THREAD

**Issue by cult-leader** [pajoma/vscode-journal#70]
When I create a new journal note, the link to it is an absolute path (e.g., /home/cultleader/Documents/journal/2020/12/23/test_note.md) as opposed to a relative path (./23/test_note.md). In the previous versions of the extension it used relative paths. Using absolute paths makes it difficult to move the journal to a different system--and the markdown preview in VSCode doesn't work with absolute paths it seems.

Is this intended behavior? Is there any way to get it back to using relative paths?

**Comment by pajoma** [comment]
No, this was not intended. I am looking into it, thanks.

**Comment by sandrogauci** [comment]
also facing this issue. Downgrading to v0.10.0 does not exhibit this bug

**Comment by pajoma** [comment]
This is related to the scopes configuration (which drags on for a while). The normalization doesn't seem to work as expected, I am working on it.
