### ISSUE TITLE
Can't place items under correct heading

### ISSUE THREAD

**Issue by lonix1** [pajoma/vscode-journal#72]
I tried:
````json
  "journal.tpl-memo-after": "## Notes",
  "journal.tpl-task-after": "## Tasks",
````

But that doesn't place items after those headings... everything ends up at the top of the file.

It also says:
> This setting is outdated, please use the setting 'templates' instead

But there's no indication how to do so?

**Comment by jfrome** [comment]
I had the same issue as resolved it by editing the User settings.json and adding the setting in journal.templates like below:

```
    "journal.templates": [
        {
            "name": "task",
            "template": "- [ ] Task: ${input}",
            "after": "## Tasks"
        },
```
I also had to set the default journal.tpl-task to empty like this:
```
    "journal.tpl-task": "",
```
I think there is some issue where the defaults are not overidden by journal.templates.

**Comment by lonix1** [comment]
Thanks, that helped, but only when using tasks.

Unfortunately it doesn't work when combined with notes. When I specify tasks AND notes using @jfrome's workaround, the stuff is added in the wrong places.

@pajoma How do we get this to work?

**Comment by pajoma** [comment]
> I think there is some issue where the defaults are not overidden by journal.templates.

I have changed the order when looking up the configurations. The extension will now check if a templates section is configured, if it fails it will check the old style. 

> Unfortunately it doesn't work when combined with notes. When I specify tasks AND notes using @jfrome's workaround, the stuff is added in the wrong places.

I am not really sure why it doesn't work in the current version. Doesn't happen with my current build, should be fixed with the next release.

**Comment by lonix1** [comment]
Cool, I can't wait to try it out!

**Comment by sklarsa** [comment]
What is the status of this? I installed the vscode-journal extension, made no configuration changes, but every item I enter using `Cmd-Shift-J` just gets sent to the top of the day's entry:
```
# Wednesday, April 21 2021

- MEMO: note test
- [ ] TASK: test

## Tasks

## Notes
```
I haven't overridden any default settings.  Using version 0.11.2

**Comment by NicolasHaeffner** [comment]
Any update here? This does not work for me unfortunately..

**Comment by pajoma** [comment]
Currently working on it ;)

**Comment by sojkin** [comment]
Hello, same issue here. 

btw, great idea with this extension!

**Comment by pajoma** [comment]
Fixed in current release
