### ISSUE TITLE
Can't compile the extension Error: Cannot find module 'node-extension.webpack.config.js'

### ISSUE THREAD

**Issue by mameen** [pajoma/vscode-journal#84]
is the file 'node-extension.webpack.config.js' missing?
Here is what I did
```
npm install
npm run compile
```

**Comment by mameen** [comment]
I got around this by using vsce instead of webpack in my fork! 
https://github.com/mameen/vscode-journal/commit/51467d01593a9ad802a8f23bcc5d787cc2f5f750

**Comment by pajoma** [comment]
Yes, I removed webpack completely, not worth the effort.
