### ISSUE TITLE
Can't change default journal location

### ISSUE THREAD

**Issue by leozhang1** [pajoma/vscode-journal#95]
Greetings!

I have tried to change the location where my journals open up by following the instructions provided but it didn't work. What did I do wrong? I added this line into my settings.json: "journal.base": "C:/Users/MyName/Documents/GitHub/MyJournal",

**Comment by mameen** [comment]
Try to switch the back-slash? `C:\Users\MyName\Documents\GitHub\MyJournal`

**Comment by pajoma** [comment]
Yes, the writing with slash "/" is used n *nix-environments and URLs, in Windows you have to use the backslash. You can open the folder in Windows Explorer, navigate to your folder and copy the address at the top.

**Comment by leozhang1** [comment]
> Try to switch the back-slash? `C:\Users\MyName\Documents\GitHub\MyJournal`

I have just tried that too and it didn't work, unfortunately :/

**Comment by leozhang1** [comment]
> > Try to switch the back-slash? `C:\Users\MyName\Documents\GitHub\MyJournal`
> 
> I have just tried that too and it didn't work, unfortunately :/

what I typed is: "journal.base": "C:\\Users\\MyName\\Documents\\GitHub\\MyJournal",

**Comment by mameen** [comment]
You may need to escape it.. try double back-slash `C:\\Users\\MyName\\Documents\\GitHub\\MyJournal`

**Comment by leozhang1** [comment]
The two slashes worked. Thank you everyone. I tried the two slashes before and it didn't work. I think it's because I have to restart vs code after doing so. Final working key-value pair: ```"journal.base": "C:\\Users\\MyName\\Documents\\GitHub\\MyJournal"```

**Comment by leozhang1** [comment]
> Hmm, this is strange. Is the command `dir C:\Users\MyName\Documents\GitHub\MyJournal` working (in the vscode terminal)?

Yes. It does work
